# Generated by Django 2.0.5 on 2018-05-23 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('email', models.EmailField(db_column='email', max_length=254, primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='username', max_length=45, unique=True)),
                ('password', models.CharField(db_column='password', max_length=100)),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('datejoined', models.DateField(blank=True, db_column='dateJoined', null=True)),
                ('lastmodifieddate', models.DateField(blank=True, db_column='lastModifiedDate', null=True)),
                ('last_login', models.DateTimeField(blank=True, db_column='lastlogin', null=True)),
                ('is_staff', models.BooleanField(db_column='superRights', default=False)),
                ('acceptedby', models.ForeignKey(db_column='acceptedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='AB', to=settings.AUTH_USER_MODEL)),
                ('lastmodifedby', models.ForeignKey(blank=True, db_column='lastModifedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='LMB', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'User',
                'swappable': 'AUTH_USER_MODEL',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
