# Generated by Django 2.0.7 on 2018-08-05 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclass',
            name='createdby',
            field=models.ForeignKey(db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ucCB', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userclass',
            name='datecreated',
            field=models.DateField(db_column='dateCreated', null=True),
        ),
        migrations.AddField(
            model_name='userclass',
            name='studentcount',
            field=models.PositiveIntegerField(db_column='studentcount', default=0),
        ),
        migrations.AddField(
            model_name='userclass',
            name='timecreated',
            field=models.TimeField(db_column='timeCreated', null=True),
        ),
    ]
