# Generated by Django 2.0.6 on 2018-07-02 09:38

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('ranges', '0002_auto_20180702_1738'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.AutoField(db_column='groupID', primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_column='groupName', max_length=45, unique=True)),
                ('datecreated', models.DateField(db_column='dateCreated', null=True)),
                ('timecreated', models.TimeField(db_column='timeCreated', null=True)),
                ('grouppoints', models.IntegerField(db_column='groupPoints', default=0, null=True)),
                ('lastmodifieddate', models.DateField(blank=True, db_column='lastModifiedDate', null=True)),
                ('lastmodifiedtime', models.TimeField(db_column='lastModifiedTime', null=True)),
            ],
            options={
                'db_table': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='GroupRange',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('datecreated', models.DateField(db_column='dateCreated', null=True)),
                ('timecreated', models.TimeField(db_column='timeCreated', null=True)),
                ('grouprangepoints', models.IntegerField(db_column='groupRangePoints', default=0, null=True)),
            ],
            options={
                'db_table': 'GroupRange',
                'verbose_name_plural': 'GroupRanges',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('groupid', models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Group')),
            ],
            options={
                'db_table': 'StudentGroup',
                'verbose_name_plural': 'StudentGroups',
            },
        ),
        migrations.CreateModel(
            name='UserClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userclass', models.CharField(db_column='class', max_length=45)),
            ],
            options={
                'db_table': 'UserClass',
                'verbose_name_plural': 'UserClass',
            },
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastmodifedby',
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_column='admin', default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, db_column='lastModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='LMB', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='lastmodifiedtime',
            field=models.TimeField(db_column='lastModifiedTime', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='user',
            name='userclass',
            field=models.CharField(db_column='userclass', default='Public', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_column='teacher', default=False),
        ),
        migrations.AddField(
            model_name='studentgroup',
            name='studentid',
            field=models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='addedby',
            field=models.ForeignKey(db_column='addedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='groupid',
            field=models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Group'),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='rangeid',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AddField(
            model_name='group',
            name='createdby',
            field=models.ForeignKey(db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='groupleader',
            field=models.ForeignKey(db_column='groupLeader', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupleader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, db_column='lastModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GLMB', to=settings.AUTH_USER_MODEL),
        ),
    ]
