# Generated by Django 2.0.7 on 2018-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180730_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userclass',
            name='userclass',
            field=models.CharField(db_column='class', max_length=45, unique=True),
        ),
    ]
