# Generated by Django 2.0.7 on 2018-08-04 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180804_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouprange',
            name='addedby',
        ),
        migrations.RemoveField(
            model_name='grouprange',
            name='groupid',
        ),
        migrations.RemoveField(
            model_name='grouprange',
            name='rangeid',
        ),
        migrations.DeleteModel(
            name='GroupRange',
        ),
    ]
