# Generated by Django 2.0.6 on 2018-06-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180626_0640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userclass',
            field=models.CharField(db_column='userclass', default='Public', max_length=45),
        ),
    ]
