# Generated by Django 2.0.6 on 2018-07-05 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180705_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeStudentGroup',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
            ],
            options={
                'managed': False,
                'db_table': 'StudentGroup',
            },
        ),
    ]
