# Generated by Django 2.0.6 on 2018-06-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180626_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='userclass',
            field=models.CharField(db_column='userclass', default='Public', max_length=45, null=True),
        ),
    ]
