# Generated by Django 2.0.6 on 2018-07-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_fakestudentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='archived',
            field=models.BooleanField(db_column='isArchived', default=False),
        ),
    ]
