# Generated by Django 2.0.6 on 2018-06-27 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180626_1516'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastmodifedby',
            new_name='lastmodifiedby',
        ),
    ]
