# Generated by Django 2.0.6 on 2018-07-06 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180705_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentgroup',
            name='studentid',
            field=models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
