# Generated by Django 2.0.6 on 2018-06-27 05:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180627_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, db_column='lastModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='LMB', to=settings.AUTH_USER_MODEL),
        ),
    ]
