# Generated by Django 2.0.6 on 2018-07-06 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180706_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='isaccepted',
            field=models.BooleanField(db_column='isaccepted', default=False),
        ),
    ]
