# Generated by Django 2.0.6 on 2018-06-27 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20180627_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lastmodifiedtime',
            field=models.TimeField(db_column='lastModifiedTime', null=True),
        ),
    ]
