# Generated by Django 2.0.6 on 2018-06-27 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20180626_0640'),
        ('accounts', '0007_user_lastmodifiedtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('groupid', models.AutoField(db_column='groupid', primary_key=True, serialize=False)),
                ('groupname', models.CharField(db_column='groupname', max_length=45, unique=True)),
            ],
            options={
                'db_table': 'Group',
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='GroupRange',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Group')),
                ('rangeid', models.ForeignKey(db_column='rangeid', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range')),
            ],
            options={
                'db_table': 'GroupRange',
                'verbose_name_plural': 'GroupRanges',
            },
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('groupid', models.ForeignKey(db_column='groupid', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Group')),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'StudentGroup',
                'verbose_name_plural': 'StudentGroups',
            },
        ),
    ]
