# Generated by Django 2.0.6 on 2018-06-27 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_group_grouprange_studentgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='createdby',
            field=models.ForeignKey(db_column='createdBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='datecreated',
            field=models.DateField(db_column='dateCreated', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='groupleader',
            field=models.ForeignKey(db_column='groupLeader', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='groupleader', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='grouppoints',
            field=models.IntegerField(db_column='groupPoints', default=0, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, db_column='lastModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='GLMB', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='group',
            name='lastmodifieddate',
            field=models.DateField(blank=True, db_column='lastModifiedDate', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='lastmodifiedtime',
            field=models.TimeField(db_column='lastModifiedTime', null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='timecreated',
            field=models.TimeField(db_column='timeCreated', null=True),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='addedby',
            field=models.ForeignKey(db_column='addedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='datecreated',
            field=models.DateField(db_column='dateCreated', null=True),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='grouprangepoints',
            field=models.IntegerField(db_column='groupRangePoints', default=0, null=True),
        ),
        migrations.AddField(
            model_name='grouprange',
            name='timecreated',
            field=models.TimeField(db_column='timeCreated', null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupid',
            field=models.AutoField(db_column='groupID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupname',
            field=models.CharField(db_column='groupName', max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='grouprange',
            name='groupid',
            field=models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Group'),
        ),
        migrations.AlterField(
            model_name='grouprange',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='grouprange',
            name='rangeid',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='groupid',
            field=models.ForeignKey(db_column='groupID', on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Group'),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='id',
            field=models.AutoField(db_column='ID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentgroup',
            name='studentid',
            field=models.ForeignKey(db_column='studentID', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
