# Generated by Django 2.0.7 on 2018-08-04 16:33

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SDLComment',
            fields=[
                ('commentid', models.AutoField(db_column='commentID', primary_key=True, serialize=False)),
                ('comment', models.CharField(db_column='comment', max_length=255, null=True)),
                ('dateposted', models.DateField(db_column='datePosted', null=True)),
                ('timeposted', models.TimeField(db_column='timePosted', null=True)),
            ],
            options={
                'verbose_name_plural': 'SDLComments',
                'db_table': 'SDLComment',
            },
        ),
        migrations.CreateModel(
            name='SDLPost',
            fields=[
                ('postid', models.AutoField(db_column='postID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='posttitle', max_length=255, null=True)),
                ('text', tinymce.models.HTMLField(db_column='posttext', default='')),
                ('datecreated', models.DateField(db_column='dateCreated', null=True)),
                ('timecreated', models.TimeField(db_column='timeCreated', null=True)),
                ('dateposted', models.DateField(db_column='datePosted', null=True)),
                ('timeposted', models.TimeField(db_column='timePosted', null=True)),
                ('lastmodifieddate', models.DateField(db_column='LastModifiedDate', null=True)),
                ('lastmodifiedtime', models.TimeField(db_column='LastModifiedTime', null=True)),
                ('postactive', models.BooleanField(db_column='postActive', default=False)),
            ],
            options={
                'verbose_name_plural': 'SDLPosts',
                'db_table': 'SDLPost',
            },
        ),
    ]
