# Generated by Django 2.0.7 on 2018-08-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SDL', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sdlpost',
            name='createdby',
            field=models.ForeignKey(db_column='createdby', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SDLcreatedby', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sdlcomment',
            name='commenter',
            field=models.ForeignKey(db_column='commenter', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sdlcomment',
            name='postid',
            field=models.ForeignKey(db_column='postid', null=True, on_delete=django.db.models.deletion.CASCADE, to='SDL.SDLPost'),
        ),
    ]
