# Generated by Django 2.0.7 on 2018-07-17 05:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('SDL', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sdlpost',
            name='createdby',
            field=models.ForeignKey(db_column='createdby', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='SDLcreatedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
