# Generated by Django 2.0.7 on 2018-07-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SDL', '0002_sdlpost_createdby'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sdlpost',
            name='isdisabled',
        ),
        migrations.AddField(
            model_name='sdlpost',
            name='postactive',
            field=models.BooleanField(db_column='postActive', default=False),
        ),
    ]
