# Generated by Django 2.0.5 on 2018-05-24 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180523_0945'),
        ('ranges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeStudents',
            fields=[
                ('dateJoined', models.DateTimeField(blank=True, db_column='dateJoined', max_length=45, null=True)),
                ('progress', models.CharField(db_column='progress', max_length=45)),
                ('teamID', models.CharField(db_column='teamID', max_length=45)),
                ('teamName', models.CharField(db_column='teamName', max_length=45)),
                ('points', models.IntegerField(db_column='points')),
                ('rangeID', models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range', unique=True)),
                ('studentID', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING,serialize=False, to=settings.AUTH_USER_MODEL, unique=True)),
            ],
            options={
                'db_table': 'RangeStudents',
                'verbose_name_plural': 'RangeStudents',
            },
        ),
        migrations.AddField(
            model_name='range',
            name='range_type',
            field=models.CharField(default='default', max_length=100),
        ),
    ]
