# Generated by Django 2.0.5 on 2018-05-26 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0004_rangestudents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rangestudents',
            options={'verbose_name_plural': 'RangeStudents'},
        ),
        migrations.AlterModelTable(
            name='rangestudents',
            table='RangeStudents',
        ),
    ]
