# Generated by Django 2.0.5 on 2018-05-26 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0005_auto_20180526_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangestudents',
            name='points',
            field=models.IntegerField(db_column='points', default=0),
        ),
        migrations.AlterField(
            model_name='rangestudents',
            name='progress',
            field=models.CharField(db_column='progress', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='rangestudents',
            name='teamID',
            field=models.CharField(db_column='teamID', max_length=45, null=True),
        ),
        migrations.AlterField(
            model_name='rangestudents',
            name='teamName',
            field=models.CharField(db_column='teamName', max_length=45, null=True),
        ),
    ]
