# Generated by Django 2.0.5 on 2018-05-26 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0006_auto_20180526_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangestudents',
            name='rangeID',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AlterField(
            model_name='rangestudents',
            name='studentID',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
