# Generated by Django 2.0.5 on 2018-05-29 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0008_range_rangeactive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.IntegerField(db_column='questionID', primary_key=True, serialize=False)),
                ('questiontype', models.CharField(choices=[('FL', 'Flag'), ('MCQ', 'Multiple Choice'), ('SA', 'Short Answer'), ('OE', 'Open Ended')], db_column='questiontype', default='FL', max_length=100)),
                ('text', models.CharField(db_column='questiontext', max_length=100)),
                ('answer', models.CharField(db_column='answer', max_length=100)),
                ('hint', models.CharField(db_column='hint', max_length=100)),
                ('topic', models.CharField(db_column='topic', max_length=100)),
                ('marks', models.IntegerField(db_column='marks')),
            ],
            options={
                'verbose_name_plural': 'Questions',
                'db_table': 'Questions',
            },
        ),
    ]
