# Generated by Django 2.0.5 on 2018-05-29 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0009_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='RangeQuestions',
            fields=[
                ('rangequestionsid', models.IntegerField(db_column='id', default=1, primary_key=True, serialize=False)),
                ('questionorder', models.IntegerField(db_column='order')),
                ('questionid', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Questions')),
                ('rangeid', models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range')),
            ],
            options={
                'verbose_name_plural': 'RangeQuestions',
                'db_table': 'RangeQuestions',
            },
        ),
    ]
