# Generated by Django 2.0.5 on 2018-05-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0010_rangequestions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangequestions',
            name='rangequestionsid',
            field=models.IntegerField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
