# Generated by Django 2.0.5 on 2018-05-29 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0011_auto_20180529_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='title',
            field=models.CharField(db_column='questiontitle', max_length=100, null=True),
        ),
    ]
