# Generated by Django 2.0.5 on 2018-06-02 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranges', '0012_questions_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='createdby',
            field=models.ForeignKey(db_column='createdBy', default='super', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CBR', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='range',
            name='datetimecreated',
            field=models.DateTimeField(blank=True, db_column='dateTimeCreated', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='datetimeend',
            field=models.DateTimeField(blank=True, db_column='dateTimeEnd', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='datetimestart',
            field=models.DateTimeField(blank=True, db_column='dateTimeStart', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, db_column='lastModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='LMBR', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='range',
            name='lastmodifieddate',
            field=models.DateField(blank=True, db_column='lastModifiedDate', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='maxscore',
            field=models.IntegerField(blank=True, db_column='maxScore', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='rangecode',
            field=models.DateField(blank=True, db_column='rangeCode', null=True),
        ),
    ]
