# Generated by Django 2.0.5 on 2018-06-02 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0013_auto_20180602_0812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='range',
            old_name='createdby',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='range',
            name='lastmodifiedby',
        ),
    ]
