# Generated by Django 2.0.5 on 2018-05-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Range',
            fields=[
                ('rangeid', models.IntegerField(db_column='rangeID', primary_key=True, serialize=False)),
                ('rangename', models.CharField(db_column='rangeName', max_length=45)),
            ],
            options={
                'db_table': 'Range',
                'verbose_name_plural': 'Ranges',
            },
        ),
    ]
