# Generated by Django 2.0.6 on 2018-07-02 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionone', models.CharField(db_column='OptionOne', max_length=100)),
                ('optiontwo', models.CharField(db_column='OptionTwo', max_length=100)),
                ('optionthree', models.CharField(db_column='OptionThree', max_length=100)),
                ('optionfour', models.CharField(db_column='OptionFour', max_length=100)),
            ],
            options={
                'db_table': 'MCQOptions',
                'verbose_name_plural': 'MCQOptions',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.AutoField(db_column='questionID', primary_key=True, serialize=False)),
                ('questiontype', models.CharField(choices=[('FL', 'Flag'), ('MCQ', 'Multiple Choice'), ('SA', 'Short Answer'), ('OE', 'Open Ended'), ('TF', 'True/False')], db_column='questiontype', default='FL', max_length=100)),
                ('title', models.CharField(db_column='questiontitle', max_length=100, null=True)),
                ('text', models.CharField(db_column='questiontext', max_length=100)),
                ('hint', models.CharField(db_column='hint', max_length=100)),
                ('marks', models.IntegerField(db_column='marks')),
            ],
            options={
                'db_table': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('topicid', models.AutoField(db_column='topicid', primary_key=True, serialize=False)),
                ('topicname', models.CharField(db_column='topicname', max_length=100, null=True)),
            ],
            options={
                'db_table': 'QuestionTopic',
                'verbose_name_plural': 'QuestionTopics',
            },
        ),
        migrations.CreateModel(
            name='RangeQuestions',
            fields=[
                ('rangequestionsid', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('answer', models.CharField(db_column='answer', max_length=100, null=True)),
                ('questionid', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Questions')),
            ],
            options={
                'db_table': 'RangeQuestions',
                'verbose_name_plural': 'RangeQuestions',
            },
        ),
        migrations.CreateModel(
            name='RangeStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateTimeField(blank=True, db_column='dateJoined', max_length=45, null=True)),
                ('progress', models.CharField(db_column='progress', max_length=45, null=True)),
                ('teamID', models.CharField(db_column='teamID', max_length=45, null=True)),
                ('teamName', models.CharField(db_column='teamName', max_length=45, null=True)),
                ('points', models.IntegerField(db_column='points', default=0)),
                ('datecompleted', models.DateField(db_column='dateCompleted', null=True)),
                ('timecompleted', models.TimeField(db_column='timeCompleted', null=True)),
                ('lastaccess', models.DateTimeField(db_column='lastaccess', null=True)),
            ],
            options={
                'db_table': 'RangeStudents',
                'verbose_name_plural': 'RangeStudents',
            },
        ),
        migrations.CreateModel(
            name='StudentQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answergiven', models.CharField(db_column='answergiven', max_length=100)),
                ('answercorrect', models.BooleanField(db_column='right/wrong', default=False)),
                ('marksawarded', models.IntegerField(db_column='marksawarded')),
                ('questionid', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Questions')),
            ],
            options={
                'db_table': 'StudentQuestions',
                'verbose_name_plural': 'StudentQuestions',
            },
        ),
        migrations.CreateModel(
            name='UnavailablePorts',
            fields=[
                ('portnumber', models.IntegerField(db_column='portNumber', primary_key=True, serialize=False)),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UnavailablePorts',
                'verbose_name_plural': 'UnavailablePorts',
            },
        ),
        migrations.AddField(
            model_name='range',
            name='createdbyusername',
            field=models.ForeignKey(db_column='createdby', default='super', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CBR', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='range',
            name='datecreated',
            field=models.DateField(blank=True, db_column='dateCreated', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='dateend',
            field=models.DateTimeField(blank=True, db_column='dateEnd', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='datestart',
            field=models.DateField(blank=True, db_column='dateStart', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='isdisabled',
            field=models.BooleanField(db_column='isDisabled', default=False),
        ),
        migrations.AddField(
            model_name='range',
            name='lastmodifiedby',
            field=models.ForeignKey(blank=True, db_column='lastModifiedBy', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='LMBR', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='range',
            name='lastmodifieddate',
            field=models.DateField(blank=True, db_column='lastModifiedDate', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='maxscore',
            field=models.IntegerField(blank=True, db_column='maxScore', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='rangeactive',
            field=models.BooleanField(db_column='rangeActive', default=False),
        ),
        migrations.AddField(
            model_name='range',
            name='rangecode',
            field=models.IntegerField(blank=True, db_column='rangeCode', null=True, unique=True),
        ),
        migrations.AddField(
            model_name='range',
            name='rangeurl',
            field=models.CharField(db_column='rangeURL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='studentsinrange',
            field=models.IntegerField(db_column='studentsInRange', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='timeend',
            field=models.TimeField(blank=True, db_column='timeEnd', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='timestart',
            field=models.TimeField(blank=True, db_column='timeStart', null=True),
        ),
        migrations.AlterField(
            model_name='range',
            name='rangeid',
            field=models.AutoField(db_column='rangeID', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='studentquestions',
            name='rangeid',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AddField(
            model_name='studentquestions',
            name='studentid',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='rangeID',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='studentID',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rangequestions',
            name='rangeid',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AddField(
            model_name='questions',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='catid', to='ranges.QuestionTopic'),
        ),
        migrations.AddField(
            model_name='mcqoptions',
            name='questionid',
            field=models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, to='ranges.Questions'),
        ),
    ]
