# Generated by Django 2.0.5 on 2018-06-02 08:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('questionid', models.IntegerField(db_column='questionID', primary_key=True, serialize=False)),
                ('questiontype', models.CharField(choices=[('FL', 'Flag'), ('MCQ', 'Multiple Choice'), ('SA', 'Short Answer'), ('OE', 'Open Ended')], db_column='questiontype', default='FL', max_length=100)),
                ('title', models.CharField(db_column='questiontitle', max_length=100, null=True)),
                ('text', models.CharField(db_column='questiontext', max_length=100)),
                ('answer', models.CharField(db_column='answer', max_length=100)),
                ('hint', models.CharField(db_column='hint', max_length=100)),
                ('topic', models.CharField(db_column='topic', max_length=100)),
                ('marks', models.IntegerField(db_column='marks')),
            ],
            options={
                'db_table': 'Questions',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='RangeQuestions',
            fields=[
                ('rangequestionsid', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('questionorder', models.IntegerField(db_column='order')),
                ('questionid', models.ForeignKey(db_column='questionID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Questions')),
            ],
            options={
                'db_table': 'RangeQuestions',
                'verbose_name_plural': 'RangeQuestions',
            },
        ),
        migrations.CreateModel(
            name='RangeStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateTimeField(blank=True, db_column='dateJoined', max_length=45, null=True)),
                ('progress', models.CharField(db_column='progress', max_length=45, null=True)),
                ('teamID', models.CharField(db_column='teamID', max_length=45, null=True)),
                ('teamName', models.CharField(db_column='teamName', max_length=45, null=True)),
                ('points', models.IntegerField(db_column='points', default=0)),
            ],
            options={
                'db_table': 'RangeStudents',
                'verbose_name_plural': 'RangeStudents',
            },
        ),
        migrations.AddField(
            model_name='range',
            name='datetimecreated',
            field=models.DateTimeField(blank=True, db_column='dateTimeCreated', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='datetimeend',
            field=models.DateTimeField(blank=True, db_column='dateTimeEnd', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='datetimestart',
            field=models.DateTimeField(blank=True, db_column='dateTimeStart', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='lastmodifieddate',
            field=models.DateField(blank=True, db_column='lastModifiedDate', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='maxscore',
            field=models.IntegerField(blank=True, db_column='maxScore', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='rangeactive',
            field=models.BooleanField(db_column='rangeActive', default=False),
        ),
        migrations.AddField(
            model_name='range',
            name='rangecode',
            field=models.DateField(blank=True, db_column='rangeCode', null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='username',
            field=models.ForeignKey(db_column='createdby', default='super', on_delete=django.db.models.deletion.DO_NOTHING, related_name='CBR', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='rangeID',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='studentID',
            field=models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rangequestions',
            name='rangeid',
            field=models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range'),
        ),
    ]
