# Generated by Django 2.0.7 on 2018-08-08 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeRangeStudents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateJoined', models.DateTimeField(blank=True, db_column='dateJoined', max_length=45, null=True)),
                ('points', models.IntegerField(db_column='points', default=0)),
                ('datecompleted', models.DateTimeField(db_column='datecompleted', null=True)),
                ('lastaccess', models.DateTimeField(db_column='lastaccess', null=True)),
            ],
            options={
                'db_table': 'RangeStudents',
                'managed': False,
            },
        ),
    ]
