# Generated by Django 2.0.6 on 2018-07-15 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20180715_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='registryid',
            field=models.CharField(db_column='registryID', max_length=255, null=True),
        ),
    ]
