# Generated by Django 2.0.7 on 2018-07-30 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20180730_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangestudents',
            name='datecompleted',
            field=models.DateTimeField(db_column='datecompleted', null=True),
        ),
    ]
