# Generated by Django 2.0.6 on 2018-07-04 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20180704_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='dateend',
            field=models.DateField(blank=True, db_column='dateEnd', null=True),
        ),
    ]
