# Generated by Django 2.0.7 on 2018-08-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20180804_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestions',
            name='answergiven',
            field=models.TextField(db_column='answergiven', null=True),
        ),
    ]
