# Generated by Django 2.0.5 on 2018-06-04 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0002_auto_20180602_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCategory',
            fields=[
                ('categoryid', models.IntegerField(db_column='categoryid', primary_key=True, serialize=False)),
                ('categoryname', models.CharField(db_column='categoryname', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='questions',
            name='topic',
        ),
        migrations.AddField(
            model_name='questions',
            name='categoryname',
            field=models.ForeignKey(db_column='categoryname', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.QuestionCategory'),
        ),
    ]
