# Generated by Django 2.0.5 on 2018-06-04 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0003_auto_20180604_0450'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questioncategory',
            options={'verbose_name_plural': 'QuestionCategories'},
        ),
        migrations.AlterModelTable(
            name='questioncategory',
            table='QuestionCategory',
        ),
    ]
