# Generated by Django 2.0.6 on 2018-06-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0003_unavailableports'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangestudents',
            name='datecompleted',
            field=models.DateField(db_column='dateCompleted', null=True),
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='timecompleted',
            field=models.TimeField(db_column='timeCompleted', null=True),
        ),
    ]
