# Generated by Django 2.0.6 on 2018-07-04 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0003_auto_20180704_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailableports',
            name='containername',
            field=models.TextField(db_column='containerName', null=True),
        ),
        migrations.AddField(
            model_name='unavailableports',
            name='datetimecreated',
            field=models.DateTimeField(db_column='dateTimeCreated', null=True),
        ),
    ]
