# Generated by Django 2.0.6 on 2018-07-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0003_questions_registryid'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='isarchived',
            field=models.BooleanField(db_column='isArchived', default=False),
        ),
    ]
