# Generated by Django 2.0.5 on 2018-06-04 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0004_auto_20180604_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='categoryid',
            field=models.ForeignKey(db_column='categoryid', default='1', on_delete=django.db.models.deletion.DO_NOTHING, related_name='catid', to='ranges.QuestionCategory'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='categoryname',
            field=models.ForeignKey(db_column='categoryname', default='hacking', on_delete=django.db.models.deletion.DO_NOTHING, related_name='catname', to='ranges.QuestionCategory'),
        ),
    ]
