# Generated by Django 2.0.6 on 2018-06-29 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0004_auto_20180629_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='rangequestions',
            name='lastaccess',
            field=models.DateTimeField(db_column='lastaccess', null=True),
        ),
    ]
