# Generated by Django 2.0.6 on 2018-07-09 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0004_rangequestions_isdisabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='range',
            name='rangeurl',
            field=models.CharField(db_column='rangeURL', max_length=50, null=True, unique=True),
        ),
    ]
