# Generated by Django 2.0.6 on 2018-07-16 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0005_auto_20180715_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='hintpenalty',
            field=models.PositiveIntegerField(db_column='hintpenalty', default=0),
        ),
        migrations.AddField(
            model_name='studentquestions',
            name='hintactivated',
            field=models.BooleanField(db_column='hintactivated', default=False),
        ),
    ]
