# Generated by Django 2.0.6 on 2018-06-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0005_rangequestions_lastaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangequestions',
            name='lastaccess',
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='lastaccess',
            field=models.DateTimeField(db_column='lastaccess', null=True),
        ),
    ]
