# Generated by Django 2.0.6 on 2018-07-09 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0005_auto_20180709_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='marks',
        ),
        migrations.AddField(
            model_name='questions',
            name='usedocker',
            field=models.BooleanField(db_column='usedocker', default=False),
        ),
        migrations.AddField(
            model_name='rangequestions',
            name='points',
            field=models.IntegerField(db_column='points', default=0),
        ),
    ]
