# Generated by Django 2.0.6 on 2018-06-29 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0006_auto_20180629_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unavailableports',
            name='portnumber',
            field=models.IntegerField(db_column='portNumber', primary_key=True, serialize=False),
        ),
    ]
