# Generated by Django 2.0.6 on 2018-07-16 04:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranges', '0006_auto_20180716_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentHints',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hintactivated', models.BooleanField(db_column='hintactivated', default=False)),
                ('questionid', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Questions')),
                ('rangeid', models.ForeignKey(db_column='rangeid', on_delete=django.db.models.deletion.CASCADE, to='ranges.Range')),
                ('studentid', models.ForeignKey(db_column='studentid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'StudentHints',
                'db_table': 'StudentHints',
            },
        ),
        migrations.RemoveField(
            model_name='studentquestions',
            name='hintactivated',
        ),
    ]
