# Generated by Django 2.0.5 on 2018-06-05 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0007_remove_questions_categoryname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questioncategory',
            name='categoryid',
            field=models.AutoField(db_column='categoryid', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='questions',
            name='questionid',
            field=models.AutoField(db_column='questionID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='range',
            name='rangeid',
            field=models.AutoField(db_column='rangeID', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rangequestions',
            name='rangequestionsid',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
