# Generated by Django 2.0.6 on 2018-07-10 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0007_auto_20180710_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='datecreated',
            field=models.DateField(blank=True, db_column='dateCreated', null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='timecreated',
            field=models.TimeField(db_column='timecreated', null=True),
        ),
    ]
