# Generated by Django 2.0.6 on 2018-07-01 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0007_auto_20180629_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='topicid',
            field=models.ForeignKey(db_column='topicid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='catid', to='ranges.QuestionTopic'),
        ),
    ]
