# Generated by Django 2.0.6 on 2018-07-17 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0008_auto_20180716_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestions',
            name='attempts',
            field=models.PositiveIntegerField(db_column='attempts', default=0),
        ),
        migrations.AlterField(
            model_name='range',
            name='maxscore',
            field=models.PositiveIntegerField(blank=True, db_column='maxScore', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='range',
            name='studentsinrange',
            field=models.PositiveIntegerField(db_column='studentsInRange', default=0, null=True),
        ),
        migrations.AlterField(
            model_name='rangequestions',
            name='points',
            field=models.PositiveIntegerField(db_column='points', default=0),
        ),
        migrations.AlterField(
            model_name='studentquestions',
            name='marksawarded',
            field=models.PositiveIntegerField(db_column='marksawarded', default=0),
        ),
        migrations.AlterField(
            model_name='unavailableports',
            name='portnumber',
            field=models.PositiveIntegerField(db_column='portNumber', primary_key=True, serialize=False),
        ),
    ]
