# Generated by Django 2.0.5 on 2018-06-05 07:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ranges', '0008_auto_20180605_0702'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answergiven', models.CharField(db_column='answergiven', max_length=100)),
                ('answercorrect', models.BooleanField(db_column='right/wrong', default=False)),
                ('marksawarded', models.IntegerField(db_column='marksawarded')),
                ('questionid', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Questions')),
                ('rangeid', models.ForeignKey(db_column='rangeID', on_delete=django.db.models.deletion.DO_NOTHING, to='ranges.Range')),
                ('studentid', models.ForeignKey(db_column='email', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
