# Generated by Django 2.0.7 on 2018-07-17 02:24

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0009_auto_20180717_0833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='text',
            field=tinymce.models.HTMLField(db_column='questiontext', default=''),
        ),
        migrations.AlterField(
            model_name='range',
            name='rangeinfo',
            field=tinymce.models.HTMLField(db_column='rangeInfo', default=''),
        ),
    ]
