# Generated by Django 2.0.5 on 2018-06-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0009_studentquestions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentquestions',
            options={'verbose_name_plural': 'StudentQuestions'},
        ),
        migrations.AlterModelTable(
            name='studentquestions',
            table='StudentQuestions',
        ),
    ]
