# Generated by Django 2.0.6 on 2018-07-10 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0009_rangequestions_registryid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcqoptions',
            name='questionid',
            field=models.OneToOneField(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, to='ranges.Questions'),
        ),
    ]
