# Generated by Django 2.0.7 on 2018-07-17 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0010_auto_20180717_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentquestions',
            name='attempts',
            field=models.PositiveIntegerField(db_column='attempts', default=1),
        ),
    ]
