# Generated by Django 2.0.5 on 2018-06-05 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0010_auto_20180605_0729'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionTopic',
            fields=[
                ('topicid', models.AutoField(db_column='topicid', primary_key=True, serialize=False)),
                ('topicname', models.CharField(db_column='topicname', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'QuestionTopics',
                'db_table': 'QuestionTopic',
            },
        ),
        migrations.RemoveField(
            model_name='questions',
            name='categoryid',
        ),
        migrations.DeleteModel(
            name='QuestionCategory',
        ),
        migrations.AddField(
            model_name='questions',
            name='topicid',
            field=models.ForeignKey(db_column='categoryid', default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='catid', to='ranges.QuestionTopic'),
        ),
    ]
