# Generated by Django 2.0.5 on 2018-06-09 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0011_auto_20180605_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='topicid',
            field=models.ForeignKey(db_column='categoryid', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='catid', to='ranges.QuestionTopic'),
        ),
    ]
