# Generated by Django 2.0.6 on 2018-07-11 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_isaccepted'),
        ('ranges', '0011_fakerange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rangestudents',
            name='teamID',
        ),
        migrations.RemoveField(
            model_name='rangestudents',
            name='teamName',
        ),
        migrations.AddField(
            model_name='rangestudents',
            name='groupname',
            field=models.ForeignKey(blank=True, db_column='groupname', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Group'),
        ),
    ]
