# Generated by Django 2.0.6 on 2018-07-11 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0012_auto_20180711_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rangestudents',
            old_name='groupname',
            new_name='groupid',
        ),
    ]
