# Generated by Django 2.0.5 on 2018-06-10 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0012_auto_20180609_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='range',
            name='rangeurl',
            field=models.CharField(db_column='rangeURL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='range',
            name='studentsinrange',
            field=models.IntegerField(db_column='studentsInRange', null=True),
        ),
        migrations.AlterField(
            model_name='range',
            name='rangecode',
            field=models.IntegerField(blank=True, db_column='rangeCode', null=True),
        ),
    ]
