# Generated by Django 2.0.5 on 2018-06-11 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0013_auto_20180610_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='questiontype',
            field=models.CharField(choices=[('FL', 'Flag'), ('MCQ', 'Multiple Choice'), ('SA', 'Short Answer'), ('OE', 'Open Ended'), ('TF', 'True/False')], db_column='questiontype', default='FL', max_length=100),
        ),
        migrations.AlterField(
            model_name='range',
            name='rangecode',
            field=models.IntegerField(blank=True, db_column='rangeCode', null=True, unique=True),
        ),
    ]
