# Generated by Django 2.0.6 on 2018-07-11 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0013_auto_20180711_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rangestudents',
            name='groupid',
            field=models.ForeignKey(blank=True, db_column='groupid', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Group'),
        ),
    ]
