# Generated by Django 2.0.6 on 2018-07-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0014_auto_20180711_1644'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='unavailableports',
            options={'ordering': ['-portnumber'], 'verbose_name_plural': 'UnavailablePorts'},
        ),
        migrations.AddField(
            model_name='range',
            name='isopen',
            field=models.BooleanField(db_column='isOpen', default=False),
        ),
    ]
