# Generated by Django 2.0.5 on 2018-06-11 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0014_auto_20180611_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='MCQOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionone', models.CharField(db_column='OptionOne', max_length=100)),
                ('optiontwo', models.CharField(db_column='OptionTwo', max_length=100)),
                ('optionthree', models.CharField(db_column='OptionThree', max_length=100)),
                ('optionfour', models.CharField(db_column='OptionFour', max_length=100)),
                ('questionid', models.ForeignKey(db_column='questionid', on_delete=django.db.models.deletion.CASCADE, to='ranges.Questions')),
            ],
            options={
                'db_table': 'MCQOptions',
                'verbose_name_plural': 'MCQOptions',
            },
        ),
    ]
