# Generated by Django 2.0.5 on 2018-06-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranges', '0015_mcqoptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='rangequestions',
            name='questionorder',
        ),
        migrations.AddField(
            model_name='rangequestions',
            name='answer',
            field=models.CharField(db_column='answer', max_length=100, null=True),
        ),
    ]
